version: '3.8'

services:
  main-db:
    image: postgres:15
    container_name: lab10-main-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lab9
    ports:
      - "5432:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data

  test-db:
    image: postgres:15
    container_name: lab10-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lab9_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_main_data:
  postgres_test_data: